apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "secret_id": "AKIDkUHbtBOQQdqwtipxy5Jb2ZH4skaVZmqi",
      "secret_key": "7L6uiRVTQNF1niwGYyMqLxSRwXBWxLgx",
      "region": "ap-hongkong"
    }
