apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: lyzhang1999/worker:env
          imagePullPolicy: Always
          name: worker
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: DB_USER
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: REDIS_HOST
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: DB_HOST
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "1280Mi"
              cpu: "1000m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
