apiVersion: redis.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
    name: redis-example
spec:
  forProvider:
    name: "redis-crossplane-example"
    availabilityZone: "ap-hongkong-2"
    memSize: 2048
    typeId: 8
    noAuth: true
    vpcidRef:
      name: "example-cvm-vpc"
    subnetIdRef:
      name: "example-redis-subnet"
