apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-redis-subnet
spec:
  forProvider:
    availabilityZone: "ap-hongkong-2"
    cidrBlock: "10.2.3.0/24"
    name: "test-crossplane-redis-subnet"
    vpcidRef:
      name: "example-cvm-vpc"
