{{ $REGISTRY:= .Values.REGISTRY | toJson | b64enc}}
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: aliyun
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $REGISTRY }}