apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: result-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $.Release.Namespace }}-result.xyx
    http:
      paths:
      - backend:
          service:
            name: result
            port:
              number: 5001
        path: /
        pathType: Prefix

