{{ $config := .Values.DB | toYaml | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: result-db-secret
type: Opaque
data:
  # .env content
  .env: {{ $config }}
  #REJfVVNFUj1wb3N0Z3JlcwpEQl9QQVNTPXBvc3RncmVzCkRCX0hPU1Q9ZGIKREJfTkFNRT1wb3N0Z3Jlcw==
