apiVersion: v1
kind: Secret
metadata:
  name: yamltoinfra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/yuxiGit/jk-dev.git
  password: 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 # your github personal access token
  username: yuxiGit
  insecure: "true"
  forceHttpBasicAuth: "true"
  enableLfs: "true"
